#!/usr/bin/env ruby

require "rubygems"

$LOAD_PATH.push(".") unless $LOAD_PATH.include?(".")
require "lib/script_environment"
require "lib/git_helper"

require "irb"

include Grit

$repo = Repo.new(File.join(File.dirname(__FILE__), "../"))

def reload!
  Dir.glob("lib/*.rb").each do |file|
    load(file)
  end
  nil
end

IRB.start(__FILE__)